# Generated by Django 4.2.18 on 2025-02-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_age_user_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='content',
            new_name='feedback_text',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='ai_response',
        ),
        migrations.AddField(
            model_name='chat',
            name='message_type',
            field=models.CharField(choices=[('user', '사용자'), ('bot', '봇')], default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='chat',
            name='session_id',
            field=models.CharField(default='default_session', max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='homepage_rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='q1_accuracy',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='q2_naturalness',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='q3_resolution',
            field=models.IntegerField(default=3),
        ),
    ]
