# Generated by Django 5.1.4 on 2025-01-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100, verbose_name='지역구')),
                ('year', models.IntegerField(verbose_name='년도')),
                ('crime_count', models.IntegerField(verbose_name='범죄 발생 건수')),
                ('population', models.IntegerField(verbose_name='인구수')),
                ('rate', models.FloatField(verbose_name='범죄율')),
            ],
            options={
                'verbose_name': '범죄율',
                'verbose_name_plural': '범죄율 목록',
                'indexes': [models.Index(fields=['district'], name='alter_manag_distric_31cc9a_idx'), models.Index(fields=['year'], name='alter_manag_year_64e6fa_idx')],
                'unique_together': {('district', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CulturalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='행사명')),
                ('district', models.CharField(max_length=100, verbose_name='지역구')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '문화축제',
                'verbose_name_plural': '문화축제 목록',
                'indexes': [models.Index(fields=['district'], name='alter_manag_distric_67cc2c_idx'), models.Index(fields=['start_date', 'end_date'], name='alter_manag_start_d_673f32_idx')],
            },
        ),
        migrations.CreateModel(
            name='CulturalFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='시설명')),
                ('facility_type', models.CharField(max_length=100, verbose_name='시설 유형')),
                ('district', models.CharField(max_length=100, verbose_name='지역구')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
                ('latitude', models.FloatField(verbose_name='위도')),
                ('longitude', models.FloatField(verbose_name='경도')),
            ],
            options={
                'verbose_name': '문화시설',
                'verbose_name_plural': '문화시설 목록',
                'indexes': [models.Index(fields=['district'], name='alter_manag_distric_9609d3_idx'), models.Index(fields=['facility_type'], name='alter_manag_facilit_27b56b_idx')],
            },
        ),
    ]
